### ISSUE TITLE
Styles applied in incorrect order with history attribute

### ISSUE THREAD

**Issue by ErlendLandro** [Palindrom/palindrom-redirect#6]
### Steps to reproduce

1. Run and build SignIn and Content (https://github.com/StarcounterApps/SignIn/commit/224070465b64212ac96fbce0f0a62e3e5eb90d84 and https://github.com/StarcounterApps/Content/commit/905a684161ab71aea94bf43103f3f33bdd024a58)
2. Sign in
3. Go to `http://localhost:8080/content/cms`
4. Click `CREATE` in the top right corner
5. Notice how there's no margin on the body since the applied CSS comes from [standalone.css](https://github.com/StarcounterApps/Content/blob/issue/38/src/Content/wwwroot/Content/css/standalone.css) in the content app 
6. Refresh the page and notice how the style `body { margin: 20px };` is applied

### Expected result

The styling should be consistent so that the page looks the same no matter if it's accessed using redirect or directly.

### Actual result

The styling is applied inconsistently.

### Screenshot
![badstyle](https://cloud.githubusercontent.com/assets/19392292/25224087/a4e0f716-25bd-11e7-8809-053894d6e958.gif)

Removing the history attribute fixes it so that the styling from `PartialToStandaloneHtmlProvider` is always applied first.

CC @tomalec @warpech 

Discovered in https://github.com/StarcounterApps/Content/pull/37

**Comment by tomalec** [comment]
Moving `<link href="/Content/css/standalone.css" rel="stylesheet" />` from imported document body (https://github.com/StarcounterApps/Content/blob/master/src/Content/wwwroot/Content/viewmodels/StandalonePage.html#L1), to view's template
https://github.com/StarcounterApps/Content/blob/master/src/Content/wwwroot/Content/viewmodels/StandalonePage.html#L4, also fixes the problem. Then CSS rules are removed once partial is removed.


However, it's a subject of app design, that sometimes uses standalone sometimes not.

**Comment by ErlendLandro** [comment]
That's great, thank you!

**Comment by warpech** [comment]
I am not satisfied with this solution. 

The problem is that the content of `standalone.css` is incorrect. We should only have BEM class selectors in stylesheets. If someone wants to have a margin in the view, they should set up the margin in `declarative-shadow-dom`, not as a style on the `html` element.

The page https://github.com/StarcounterApps/Content/blob/b0f5cbc3c4120de44efc073ce3b2202b4b2b196e/src/Content/wwwroot/Content/viewmodels/StandalonePage.html should be BEM-ified to have only `<starcounter-include partial="{{model.CurrentPage}}"></starcounter-include>` in the Light DOM.

The `User` area should be removed in my opinion.

If we follow BEM, then the only difference between putting `<link href="/Content/css/standalone.css" rel="stylesheet" />` outside or inside of the `<template>` tag is if it will be loaded and applied once (at template loading) or multiple times (at template stamping).

**Comment by warpech** [comment]
Just noticed that the above solution is actually advised in https://github.com/StarcounterApps/Content/issues/39.

Feel free to close this then.

Thanks!

**Comment by ErlendLandro** [comment]
Closing in favor of StarcounterApps/Content#39
